#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

usage() {
  cat <<'USAGE'
Usage:
  ./scripts/prod_gate_bundle_verify.sh \
    [--run-report-json PATH] \
    [--bundle-dir PATH] \
    [--bundle-tar PATH] \
    [--bundle-tar-sha256-file PATH] \
    [--check-tar-sha256 [0|1]] \
    [--check-manifest [0|1]] \
    [--show-details [0|1]]

Purpose:
  Verify production bundle integrity artifacts generated by prod_gate_bundle.sh:
  - tarball checksum sidecar (<bundle>.tar.gz.sha256)
  - in-bundle manifest (manifest.sha256)

Notes:
  - Provide at least one of --run-report-json, --bundle-dir, or --bundle-tar.
  - --run-report-json can auto-fill bundle_dir, bundle_tar, and checksum sidecar paths.
  - If --bundle-dir is omitted and --check-manifest=1, the tarball is extracted to a temp dir for manifest verification.
USAGE
}

need_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "missing required command: $1"
    exit 2
  fi
}

bool_arg_or_die() {
  local name="$1"
  local value="$2"
  if [[ "$value" != "0" && "$value" != "1" ]]; then
    echo "$name must be 0 or 1"
    exit 2
  fi
}

json_string_field() {
  local file="$1"
  local key="$2"
  sed -nE "s/^[[:space:]]*\"${key}\":[[:space:]]*\"([^\"]*)\".*/\1/p" "$file" | head -n1
}

sha256_tool=""

detect_sha256_tool() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256_tool="sha256sum"
    return
  fi
  if command -v shasum >/dev/null 2>&1; then
    sha256_tool="shasum"
    return
  fi
  echo "missing required command: sha256sum or shasum"
  exit 2
}

sha256_value() {
  local file="$1"
  local line=""
  if [[ "$sha256_tool" == "sha256sum" ]]; then
    line="$(sha256sum "$file")"
  else
    line="$(shasum -a 256 "$file")"
  fi
  printf '%s' "${line%% *}"
}

run_report_json=""
bundle_dir=""
bundle_tar=""
bundle_tar_sha256_file=""
check_tar_sha256="${PROD_GATE_BUNDLE_VERIFY_CHECK_TAR_SHA256:-1}"
check_manifest="${PROD_GATE_BUNDLE_VERIFY_CHECK_MANIFEST:-1}"
show_details="${PROD_GATE_BUNDLE_VERIFY_SHOW_DETAILS:-0}"
check_tar_sha256_set=0
bundle_tar_explicit=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --run-report-json)
      run_report_json="${2:-}"
      shift 2
      ;;
    --bundle-dir)
      bundle_dir="${2:-}"
      shift 2
      ;;
    --bundle-tar)
      bundle_tar="${2:-}"
      bundle_tar_explicit=1
      shift 2
      ;;
    --bundle-tar-sha256-file)
      bundle_tar_sha256_file="${2:-}"
      shift 2
      ;;
    --check-tar-sha256)
      if [[ $# -ge 2 && ( "${2:-}" == "0" || "${2:-}" == "1" ) ]]; then
        check_tar_sha256="${2:-}"
        check_tar_sha256_set=1
        shift 2
      else
        check_tar_sha256="1"
        check_tar_sha256_set=1
        shift
      fi
      ;;
    --check-manifest)
      if [[ $# -ge 2 && ( "${2:-}" == "0" || "${2:-}" == "1" ) ]]; then
        check_manifest="${2:-}"
        shift 2
      else
        check_manifest="1"
        shift
      fi
      ;;
    --show-details)
      if [[ $# -ge 2 && ( "${2:-}" == "0" || "${2:-}" == "1" ) ]]; then
        show_details="${2:-}"
        shift 2
      else
        show_details="1"
        shift
      fi
      ;;
    -h|--help|help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1"
      usage
      exit 2
      ;;
  esac
done

for cmd in bash tar find sed grep sort mktemp head; do
  need_cmd "$cmd"
done
detect_sha256_tool

bool_arg_or_die "--check-tar-sha256" "$check_tar_sha256"
bool_arg_or_die "--check-manifest" "$check_manifest"
bool_arg_or_die "--show-details" "$show_details"

if [[ -n "$run_report_json" ]]; then
  if [[ ! -f "$run_report_json" ]]; then
    echo "run report JSON file not found: $run_report_json"
    exit 1
  fi
  if [[ -z "$bundle_dir" ]]; then
    bundle_dir="$(json_string_field "$run_report_json" "bundle_dir")"
  fi
  if [[ -z "$bundle_tar" ]]; then
    bundle_tar="$(json_string_field "$run_report_json" "bundle_tar")"
    if [[ -n "$bundle_tar" ]]; then
      bundle_tar_explicit=1
    fi
  fi
  if [[ -z "$bundle_tar_sha256_file" ]]; then
    bundle_tar_sha256_file="$(json_string_field "$run_report_json" "bundle_tar_sha256_file")"
  fi
fi
if [[ -z "$bundle_tar" && -n "$bundle_dir" ]]; then
  bundle_tar="${bundle_dir}.tar.gz"
fi
if [[ -z "$bundle_tar_sha256_file" && -n "$bundle_tar" ]]; then
  bundle_tar_sha256_file="${bundle_tar}.sha256"
fi

if [[ -z "$run_report_json" && -z "$bundle_dir" && -z "$bundle_tar" ]]; then
  echo "missing required input: provide --run-report-json, --bundle-dir, and/or --bundle-tar"
  exit 2
fi

# If the caller only provided --bundle-dir, default tar checksum checks are skipped.
if [[ "$bundle_tar_explicit" == "0" && "$check_tar_sha256" == "1" && "$check_tar_sha256_set" == "0" ]]; then
  check_tar_sha256="0"
fi

if [[ -n "$bundle_dir" && ! -d "$bundle_dir" ]]; then
  echo "bundle dir not found: $bundle_dir"
  exit 1
fi
need_bundle_tar_file=0
if [[ "$bundle_tar_explicit" == "1" || "$check_tar_sha256" == "1" || ( "$check_manifest" == "1" && -z "$bundle_dir" ) ]]; then
  need_bundle_tar_file=1
fi
if [[ "$need_bundle_tar_file" == "1" && -n "$bundle_tar" && ! -f "$bundle_tar" ]]; then
  echo "bundle tar not found: $bundle_tar"
  exit 1
fi
if [[ -n "$bundle_tar_sha256_file" && -z "$bundle_tar" ]]; then
  echo "--bundle-tar-sha256-file requires --bundle-tar"
  exit 2
fi

if [[ "$check_tar_sha256" == "0" && "$check_manifest" == "0" ]]; then
  echo "no checks enabled (set --check-tar-sha256=1 and/or --check-manifest=1)"
  exit 2
fi

tmp_extract_dir=""
cleanup() {
  if [[ -n "$tmp_extract_dir" && -d "$tmp_extract_dir" ]]; then
    rm -rf "$tmp_extract_dir"
  fi
}
trap cleanup EXIT

issues=0

if [[ "$check_tar_sha256" == "1" ]]; then
  if [[ -z "$bundle_tar" ]]; then
    echo "tarball checksum check requested but --bundle-tar is missing"
    issues=$((issues + 1))
  else
    local_sidecar="$bundle_tar_sha256_file"
    if [[ -z "$local_sidecar" ]]; then
      local_sidecar="${bundle_tar}.sha256"
    fi
    if [[ ! -f "$local_sidecar" ]]; then
      echo "tarball checksum sidecar missing: $local_sidecar"
      issues=$((issues + 1))
    else
      line="$(head -n1 "$local_sidecar" || true)"
      if [[ "$line" =~ ^([A-Fa-f0-9]{64})[[:space:]][[:space:]](.+)$ ]]; then
        expected="${BASH_REMATCH[1],,}"
        label="${BASH_REMATCH[2]}"
        actual="$(sha256_value "$bundle_tar")"
        if [[ "$actual" == "$expected" ]]; then
          if [[ "$show_details" == "1" ]]; then
            echo "tarball checksum ok: $bundle_tar label=$label"
          fi
        else
          echo "tarball checksum mismatch: $bundle_tar expected=$expected actual=$actual"
          issues=$((issues + 1))
        fi
      else
        echo "invalid tarball checksum sidecar format: $local_sidecar"
        issues=$((issues + 1))
      fi
    fi
  fi
fi

manifest_bundle_dir="$bundle_dir"
if [[ "$check_manifest" == "1" && -z "$manifest_bundle_dir" ]]; then
  if [[ -z "$bundle_tar" ]]; then
    echo "manifest check requested but no --bundle-dir or --bundle-tar provided"
    issues=$((issues + 1))
  else
    tmp_extract_dir="$(mktemp -d)"
    if ! tar -xzf "$bundle_tar" -C "$tmp_extract_dir"; then
      echo "failed to extract bundle tar: $bundle_tar"
      issues=$((issues + 1))
    else
      extracted_dir=""
      while IFS= read -r d; do
        [[ -z "$d" ]] && continue
        if [[ -z "$extracted_dir" ]]; then
          extracted_dir="$d"
        else
          extracted_dir=""
          break
        fi
      done < <(find "$tmp_extract_dir" -mindepth 1 -maxdepth 1 -type d | sort)
      if [[ -z "$extracted_dir" ]]; then
        echo "could not determine extracted bundle directory in: $tmp_extract_dir"
        issues=$((issues + 1))
      else
        manifest_bundle_dir="$extracted_dir"
      fi
    fi
  fi
fi

if [[ "$check_manifest" == "1" && -n "$manifest_bundle_dir" ]]; then
  manifest_file="$manifest_bundle_dir/manifest.sha256"
  if [[ ! -f "$manifest_file" ]]; then
    echo "manifest not found: $manifest_file"
    issues=$((issues + 1))
  else
    manifest_count=0
    while IFS= read -r line || [[ -n "$line" ]]; do
      [[ -z "$line" ]] && continue
      if [[ "$line" =~ ^([A-Fa-f0-9]{64})[[:space:]][[:space:]](.+)$ ]]; then
        expected="${BASH_REMATCH[1],,}"
        rel_path="${BASH_REMATCH[2]}"
        file_path="$manifest_bundle_dir/$rel_path"
        manifest_count=$((manifest_count + 1))
        if [[ ! -f "$file_path" ]]; then
          echo "manifest entry missing file: $rel_path"
          issues=$((issues + 1))
          continue
        fi
        actual="$(sha256_value "$file_path")"
        if [[ "$actual" != "$expected" ]]; then
          echo "manifest checksum mismatch: $rel_path expected=$expected actual=$actual"
          issues=$((issues + 1))
        elif [[ "$show_details" == "1" ]]; then
          echo "manifest checksum ok: $rel_path"
        fi
      else
        echo "invalid manifest line format: $line"
        issues=$((issues + 1))
      fi
    done <"$manifest_file"

    if ((manifest_count == 0)); then
      echo "manifest has no entries: $manifest_file"
      issues=$((issues + 1))
    fi
  fi
fi

if ((issues > 0)); then
  echo "[prod-gate-bundle-verify] failed (issues=$issues)"
  exit 1
fi

echo "[prod-gate-bundle-verify] ok"
if [[ -n "$run_report_json" ]]; then
  echo "[prod-gate-bundle-verify] run_report_json=$run_report_json"
fi
if [[ -n "$manifest_bundle_dir" ]]; then
  echo "[prod-gate-bundle-verify] bundle_dir=$manifest_bundle_dir"
fi
if [[ -n "$bundle_tar" ]]; then
  echo "[prod-gate-bundle-verify] bundle_tar=$bundle_tar"
fi
