#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

usage() {
  cat <<'USAGE'
Usage:
  ./scripts/prod_pilot_cohort_bundle_verify.sh \
    [--summary-json PATH] \
    [--reports-dir PATH] \
    [--bundle-tar PATH] \
    [--bundle-sha256-file PATH] \
    [--bundle-manifest-json PATH] \
    [--check-tar-sha256 [0|1]] \
    [--check-manifest [0|1]] \
    [--show-details [0|1]]

Purpose:
  Verify sustained-pilot cohort bundle artifacts generated by
  prod_pilot_cohort_runbook:
  - tarball checksum sidecar (<bundle>.tar.gz.sha256)
  - cohort bundle manifest JSON (prod_pilot_cohort_bundle_manifest.json)
  - bundle structure (round directories and run report list)

Notes:
  - Provide at least one of --summary-json, --reports-dir, or --bundle-tar.
  - --summary-json can auto-fill reports_dir, bundle_tar, checksum sidecar,
    and bundle manifest paths from cohort summary artifacts.
USAGE
}

need_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "missing required command: $1"
    exit 2
  fi
}

bool_or_die() {
  local name="$1"
  local value="$2"
  if [[ "$value" != "0" && "$value" != "1" ]]; then
    echo "$name must be 0 or 1"
    exit 2
  fi
}

trim() {
  local value="$1"
  value="${value#"${value%%[![:space:]]*}"}"
  value="${value%"${value##*[![:space:]]}"}"
  printf '%s' "$value"
}

abs_path() {
  local path
  path="$(trim "${1:-}")"
  if [[ -z "$path" ]]; then
    echo ""
    return
  fi
  if [[ "$path" == /* ]]; then
    echo "$path"
  else
    echo "$ROOT_DIR/$path"
  fi
}

sha256_tool=""
detect_sha256_tool() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256_tool="sha256sum"
    return
  fi
  if command -v shasum >/dev/null 2>&1; then
    sha256_tool="shasum"
    return
  fi
  if command -v openssl >/dev/null 2>&1; then
    sha256_tool="openssl"
    return
  fi
  echo "missing required command: sha256sum or shasum or openssl"
  exit 2
}

sha256_value() {
  local file="$1"
  case "$sha256_tool" in
    sha256sum)
      sha256sum "$file" | awk '{print $1}'
      ;;
    shasum)
      shasum -a 256 "$file" | awk '{print $1}'
      ;;
    openssl)
      openssl dgst -sha256 "$file" | awk '{print $NF}'
      ;;
    *)
      return 1
      ;;
  esac
}

json_string_field() {
  local file="$1"
  local jq_path="$2"
  jq -r "$jq_path // \"\"" "$file" 2>/dev/null || true
}

summary_json=""
reports_dir=""
bundle_tar=""
bundle_sha256_file=""
bundle_manifest_json=""
check_tar_sha256="${PROD_PILOT_COHORT_BUNDLE_VERIFY_CHECK_TAR_SHA256:-1}"
check_manifest="${PROD_PILOT_COHORT_BUNDLE_VERIFY_CHECK_MANIFEST:-1}"
show_details="${PROD_PILOT_COHORT_BUNDLE_VERIFY_SHOW_DETAILS:-0}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --summary-json)
      summary_json="${2:-}"
      shift 2
      ;;
    --reports-dir)
      reports_dir="${2:-}"
      shift 2
      ;;
    --bundle-tar)
      bundle_tar="${2:-}"
      shift 2
      ;;
    --bundle-sha256-file)
      bundle_sha256_file="${2:-}"
      shift 2
      ;;
    --bundle-manifest-json)
      bundle_manifest_json="${2:-}"
      shift 2
      ;;
    --check-tar-sha256)
      if [[ $# -ge 2 && ( "${2:-}" == "0" || "${2:-}" == "1" ) ]]; then
        check_tar_sha256="${2:-}"
        shift 2
      else
        check_tar_sha256="1"
        shift
      fi
      ;;
    --check-manifest)
      if [[ $# -ge 2 && ( "${2:-}" == "0" || "${2:-}" == "1" ) ]]; then
        check_manifest="${2:-}"
        shift 2
      else
        check_manifest="1"
        shift
      fi
      ;;
    --show-details)
      if [[ $# -ge 2 && ( "${2:-}" == "0" || "${2:-}" == "1" ) ]]; then
        show_details="${2:-}"
        shift 2
      else
        show_details="1"
        shift
      fi
      ;;
    -h|--help|help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1"
      usage
      exit 2
      ;;
  esac
done

for cmd in bash jq tar find sort mktemp head grep sed dirname; do
  need_cmd "$cmd"
done
detect_sha256_tool

bool_or_die "--check-tar-sha256" "$check_tar_sha256"
bool_or_die "--check-manifest" "$check_manifest"
bool_or_die "--show-details" "$show_details"

summary_json="$(abs_path "$summary_json")"
reports_dir="$(abs_path "$reports_dir")"
bundle_tar="$(abs_path "$bundle_tar")"
bundle_sha256_file="$(abs_path "$bundle_sha256_file")"
bundle_manifest_json="$(abs_path "$bundle_manifest_json")"

if [[ -n "$summary_json" ]]; then
  if [[ ! -f "$summary_json" ]]; then
    echo "cohort summary JSON not found: $summary_json"
    exit 1
  fi
  if [[ -z "$reports_dir" ]]; then
    reports_dir="$(json_string_field "$summary_json" '.artifacts.reports_dir')"
    reports_dir="$(abs_path "$reports_dir")"
  fi
  if [[ -z "$bundle_tar" ]]; then
    bundle_tar="$(json_string_field "$summary_json" '.artifacts.bundle_tar')"
    bundle_tar="$(abs_path "$bundle_tar")"
  fi
  if [[ -z "$bundle_sha256_file" ]]; then
    bundle_sha256_file="$(json_string_field "$summary_json" '.artifacts.bundle_sha256_file')"
    bundle_sha256_file="$(abs_path "$bundle_sha256_file")"
  fi
  if [[ -z "$bundle_manifest_json" ]]; then
    bundle_manifest_json="$(json_string_field "$summary_json" '.artifacts.bundle_manifest_json')"
    bundle_manifest_json="$(abs_path "$bundle_manifest_json")"
  fi
fi

if [[ -z "$bundle_tar" && -n "$reports_dir" ]]; then
  bundle_tar="${reports_dir}.tar.gz"
fi
if [[ -z "$bundle_sha256_file" && -n "$bundle_tar" ]]; then
  bundle_sha256_file="${bundle_tar}.sha256"
fi
if [[ -z "$bundle_manifest_json" && -n "$reports_dir" ]]; then
  bundle_manifest_json="${reports_dir}/prod_pilot_cohort_bundle_manifest.json"
fi

if [[ -z "$summary_json" && -z "$reports_dir" && -z "$bundle_tar" ]]; then
  echo "missing required input: provide --summary-json, --reports-dir, and/or --bundle-tar"
  exit 2
fi
if [[ "$check_tar_sha256" == "0" && "$check_manifest" == "0" ]]; then
  echo "no checks enabled (set --check-tar-sha256=1 and/or --check-manifest=1)"
  exit 2
fi

issues=0
tmp_extract_dir=""
extract_root_dir=""
cleanup() {
  if [[ -n "$tmp_extract_dir" && -d "$tmp_extract_dir" ]]; then
    rm -rf "$tmp_extract_dir"
  fi
}
trap cleanup EXIT

if [[ "$check_tar_sha256" == "1" ]]; then
  if [[ -z "$bundle_tar" ]]; then
    echo "tarball checksum check requested but bundle tar is not resolved"
    issues=$((issues + 1))
  elif [[ ! -f "$bundle_tar" ]]; then
    echo "bundle tar not found: $bundle_tar"
    issues=$((issues + 1))
  elif [[ -z "$bundle_sha256_file" || ! -f "$bundle_sha256_file" ]]; then
    echo "bundle sha256 sidecar not found: $bundle_sha256_file"
    issues=$((issues + 1))
  else
    line="$(head -n1 "$bundle_sha256_file" || true)"
    if [[ "$line" =~ ^([A-Fa-f0-9]{64})[[:space:]][[:space:]](.+)$ ]]; then
      expected="${BASH_REMATCH[1],,}"
      actual="$(sha256_value "$bundle_tar" | tr '[:upper:]' '[:lower:]')"
      if [[ "$actual" != "$expected" ]]; then
        echo "bundle tar checksum mismatch: expected=$expected actual=$actual"
        issues=$((issues + 1))
      elif [[ "$show_details" == "1" ]]; then
        echo "bundle tar checksum ok: $bundle_tar"
      fi
    else
      echo "invalid bundle sha256 sidecar format: $bundle_sha256_file"
      issues=$((issues + 1))
    fi
  fi
fi

if [[ "$check_manifest" == "1" ]]; then
  manifest_path="$bundle_manifest_json"
  if [[ -n "$manifest_path" && ! -f "$manifest_path" ]]; then
    manifest_path=""
  fi

  if [[ -z "$manifest_path" && -n "$reports_dir" && -d "$reports_dir" ]]; then
    candidate="$reports_dir/prod_pilot_cohort_bundle_manifest.json"
    if [[ -f "$candidate" ]]; then
      manifest_path="$candidate"
    fi
  fi

  if [[ -z "$manifest_path" && -n "$bundle_tar" && -f "$bundle_tar" ]]; then
    tmp_extract_dir="$(mktemp -d)"
    if ! tar -xzf "$bundle_tar" -C "$tmp_extract_dir"; then
      echo "failed to extract bundle tar for manifest validation: $bundle_tar"
      issues=$((issues + 1))
    else
      while IFS= read -r d; do
        [[ -z "$d" ]] && continue
        if [[ -z "$extract_root_dir" ]]; then
          extract_root_dir="$d"
        else
          extract_root_dir=""
          break
        fi
      done < <(find "$tmp_extract_dir" -mindepth 1 -maxdepth 1 -type d | sort)
      if [[ -n "$extract_root_dir" ]]; then
        candidate="$extract_root_dir/prod_pilot_cohort_bundle_manifest.json"
        if [[ -f "$candidate" ]]; then
          manifest_path="$candidate"
        fi
      fi
    fi
  fi

  if [[ -z "$manifest_path" || ! -f "$manifest_path" ]]; then
    echo "cohort bundle manifest not found"
    issues=$((issues + 1))
  else
    required_paths=(
      '.generated_at'
      '.reports_dir'
      '.report_list_file'
      '.trend_summary_json'
      '.alert_summary_json'
      '.summary_json'
      '.run_reports'
      '.round_results'
    )
    for path in "${required_paths[@]}"; do
      if ! jq -e "$path" "$manifest_path" >/dev/null 2>&1; then
        echo "manifest missing required field: $path"
        issues=$((issues + 1))
      fi
    done
    if ! jq -e '.run_reports | type == "array"' "$manifest_path" >/dev/null 2>&1; then
      echo "manifest run_reports must be an array"
      issues=$((issues + 1))
    fi
    if ! jq -e '.round_results | type == "array"' "$manifest_path" >/dev/null 2>&1; then
      echo "manifest round_results must be an array"
      issues=$((issues + 1))
    fi
    rr_count="$(jq -r '.run_reports | length' "$manifest_path" 2>/dev/null || echo 0)"
    if [[ ! "$rr_count" =~ ^[0-9]+$ ]] || ((rr_count < 1)); then
      echo "manifest run_reports must include at least one report"
      issues=$((issues + 1))
    fi
  fi

  structural_dir=""
  if [[ -n "$reports_dir" && -d "$reports_dir" ]]; then
    structural_dir="$reports_dir"
  elif [[ -n "$extract_root_dir" && -d "$extract_root_dir" ]]; then
    structural_dir="$extract_root_dir"
  fi

  if [[ -n "$structural_dir" ]]; then
    if [[ ! -s "$structural_dir/run_reports.list" ]]; then
      echo "cohort run_reports.list missing or empty: $structural_dir/run_reports.list"
      issues=$((issues + 1))
    fi
    round_dir_count="$(find "$structural_dir" -mindepth 1 -maxdepth 1 -type d -name 'round_*' | wc -l | tr -d ' ')"
    if [[ ! "$round_dir_count" =~ ^[0-9]+$ ]] || ((round_dir_count < 1)); then
      echo "cohort bundle has no round_* directories: $structural_dir"
      issues=$((issues + 1))
    fi
    while IFS= read -r rd; do
      [[ -z "$rd" ]] && continue
      if [[ ! -f "$rd/prod_pilot_round.log" ]]; then
        echo "missing round log: $rd/prod_pilot_round.log"
        issues=$((issues + 1))
      fi
    done < <(find "$structural_dir" -mindepth 1 -maxdepth 1 -type d -name 'round_*' | sort)
  fi
fi

if ((issues > 0)); then
  echo "[prod-pilot-cohort-bundle-verify] failed (issues=$issues)"
  exit 1
fi

echo "[prod-pilot-cohort-bundle-verify] ok"
if [[ -n "$summary_json" ]]; then
  echo "[prod-pilot-cohort-bundle-verify] summary_json=$summary_json"
fi
if [[ -n "$reports_dir" ]]; then
  echo "[prod-pilot-cohort-bundle-verify] reports_dir=$reports_dir"
fi
if [[ -n "$bundle_tar" ]]; then
  echo "[prod-pilot-cohort-bundle-verify] bundle_tar=$bundle_tar"
fi
